# Generated by Django 2.2.6 on 2021-07-29 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210728_1547'),
        ('users', '0002_auto_20210728_1951'),
    ]

    operations = [
    ]
