# Generated by Django 2.2.6 on 2021-07-29 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210730_0106'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registrationemail',
            options={'verbose_name': 'Email для аутентификации', 'verbose_name_plural': 'Email для аутентификации'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
