# Generated by Django 2.2.6 on 2021-07-31 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210801_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'user'), ('moderator', 'moderator'), ('admin', 'admin')], default=('user', 'user'), max_length=16, verbose_name='Права доступа'),
        ),
    ]
